//! Provider/model validation against the pi catalog snapshot
//! (web/providers.json, regenerated by tools/gen-providers.mjs). Agent
//! creation rejects providers/models pi can't resolve, so a bad manifest
//! fails fast at the control plane instead of crash-looping pi inside the
//! VM (an unknown provider makes `pi --mode rpc` exit at spawn; prompts
//! then hang into RPC timeouts and the chat stays silent).

use anyhow::{bail, Result};
use serde_json::Value;
use std::sync::OnceLock;

const CATALOG_JSON: &str = include_str!("../../../web/providers.json");

fn catalog() -> &'static Value {
    static CAT: OnceLock<Value> = OnceLock::new();
    CAT.get_or_init(|| {
        serde_json::from_str(CATALOG_JSON).expect("web/providers.json is valid JSON")
    })
}

/// The raw providers.json document (provider/model lists), for handlers
/// that annotate it with runtime state.
pub fn providers_json() -> &'static Value {
    catalog()
}

/// Closest catalog key by substring containment (either direction), for
/// "did you mean …" hints (e.g. "kimi" → "kimi-coding").
fn suggest<'a>(needle: &str, candidates: impl Iterator<Item = &'a str>) -> Option<String> {
    let needle = needle.to_lowercase();
    let mut best: Option<&str> = None;
    for c in candidates {
        let cl = c.to_lowercase();
        if (cl.contains(&needle) || needle.contains(&cl)) && best.is_none_or(|b| c.len() < b.len())
        {
            best = Some(c);
        }
    }
    best.map(str::to_string)
}

/// Validate that pi can resolve `provider`/`model`, and that the provider
/// can actually receive an API key inside the VM (env mapping exists).
pub fn validate_model(provider: &str, model: &str) -> Result<()> {
    let providers = catalog()["providers"]
        .as_object()
        .expect("providers object");
    let Some(entry) = providers.get(provider) else {
        let hint = suggest(provider, providers.keys().map(String::as_str))
            .map(|s| format!(" — did you mean '{s}'?"))
            .unwrap_or_default();
        bail!(
            "unknown provider '{provider}'{hint} pi supports: {}",
            providers.keys().cloned().collect::<Vec<_>>().join(", ")
        );
    };
    if suzerain_protocol::secrets::provider_env_and_host(provider).is_none() {
        bail!(
            "provider '{provider}' can't receive an API key inside the agent VM \
             (OAuth-only or per-deployment endpoint); choose a key-based provider"
        );
    }
    let models: Vec<&str> = entry["models"]
        .as_array()
        .map(|ms| ms.iter().filter_map(|m| m["id"].as_str()).collect())
        .unwrap_or_default();
    // openrouter's live catalog (thousands of models, changing daily —
    // including short-lived free/stealth releases) is never fully captured
    // by our static pi-package snapshot; skip the membership check and let
    // openrouter itself reject an unknown id at request time.
    if provider != "openrouter" && !models.is_empty() && !models.contains(&model) {
        let hint = suggest(model, models.iter().copied())
            .map(|s| format!("; did you mean '{s}'?"))
            .unwrap_or_default();
        bail!(
            "unknown model '{model}' for provider '{provider}'{hint} \
             ({count} models in catalog)",
            count = models.len()
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::validate_model;

    #[test]
    fn accepts_catalog_pairs() {
        assert!(validate_model("kimi-coding", "kimi-for-coding").is_ok());
        assert!(validate_model("anthropic", "claude-haiku-4-5").is_ok());
    }

    #[test]
    fn rejects_unknown_provider_with_hint() {
        let err = validate_model("kimi", "k3").unwrap_err().to_string();
        assert!(err.contains("did you mean 'kimi-coding'"), "{err}");
    }

    #[test]
    fn rejects_unknown_model() {
        let err = validate_model("anthropic", "gpt-5")
            .unwrap_err()
            .to_string();
        assert!(err.contains("unknown model"), "{err}");
    }

    #[test]
    fn accepts_any_model_for_openrouter() {
        assert!(validate_model("openrouter", "stealth/ox-alpha").is_ok());
    }

    #[test]
    fn rejects_providers_without_key_injection() {
        for p in ["openai-codex", "amazon-bedrock", "azure-openai-responses"] {
            let err = validate_model(p, "anything").unwrap_err().to_string();
            assert!(err.contains("can't receive an API key"), "{p}: {err}");
        }
    }
}
