#!/usr/bin/env bash
# Ensure a C toolchain is available for cargo builds.
#
# Some build dependencies (e.g. aws-lc-sys) compile C/assembly and cargo links
# Rust binaries via `cc`. On minimal systems no C compiler is installed, and
# apt requires interactive sudo. When that happens we fall back to zig's
# `zig cc`, which mise can install without root.
#
# The generated `cc`/`c++` wrappers also translate Rust-style target triples
# (`x86_64-unknown-linux-gnu`) into zig's format (`x86_64-linux-gnu`), since
# `zig cc` rejects the `-unknown-` vendor component passed by the `cc` crate.
set -euo pipefail

have_cc() {
  [ -n "${CC:-}" ] && command -v "$CC" >/dev/null 2>&1 && return 0
  command -v cc >/dev/null 2>&1 && return 0
  command -v gcc >/dev/null 2>&1 && return 0
  command -v clang >/dev/null 2>&1 && return 0
  return 1
}

if have_cc; then
  echo "[ensure-cc] C compiler found: $(command -v "${CC:-cc}" || command -v gcc || command -v clang)"
  exit 0
fi

echo "[ensure-cc] no C compiler found; installing zig to use as 'zig cc' fallback"
mise install zig@latest

ZIG="$HOME/.local/share/mise/installs/zig/latest/zig"
if [ ! -x "$ZIG" ]; then
  echo "[ensure-cc] ERROR: expected zig at $ZIG" >&2
  exit 1
fi

install -d "$HOME/.local/bin"

for tool in cc c++; do
  cat > "$HOME/.local/bin/$tool" <<EOF
#!/usr/bin/env bash
# Generated by ops/ensure-cc.sh — wraps 'zig $tool' as a system C toolchain.
# Raise the soft fd limit to the hard limit: linking large binaries opens
# >1024 object files and otherwise fails with ProcessFdQuotaExceeded on
# systems whose soft nofile limit is 1024.
ulimit -Sn "\$(ulimit -Hn)" 2>/dev/null || true
args=()
for arg in "\$@"; do
  case "\$arg" in
    --target=*-unknown-linux-*)
      arg="\${arg/-unknown-linux-/-linux-}"
      ;;
  esac
  args+=("\$arg")
done
exec "$ZIG" $tool "\${args[@]}"
EOF
  chmod 755 "$HOME/.local/bin/$tool"
done

echo "[ensure-cc] installed zig-backed cc/c++ wrappers in ~/.local/bin"
